[server]
name = "derivatives-service"
environment = "dev"
zone = "shanghai"

[http]
addr = ":8091"
timeout = "5s"

[grpc]
addr = ":9011"
timeout = "5s"

[mysql]
dsn = "root:root@tcp(127.0.0.1:3306)/financial_derivatives?charset=utf8mb4&parseTime=True&loc=Local"
