apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "marketdata.fullname" . }
  labels:
    {- include "marketdata.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "marketdata.selectorLabels" . | nindent 6 }
