apiVersion: v1
kind: Service
metadata:
  name: { include "monitoringanalytics.fullname" . }
  labels:
    {- include "monitoringanalytics.labels" . | nindent 4 }
spec:
  type: { .Values.service.type }
  ports:
    - port: { .Values.service.httpPort }
      targetPort: http
      protocol: TCP
      name: http
    - port: { .Values.service.grpcPort }
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {- include "monitoringanalytics.selectorLabels" . | nindent 4 }
