apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "clearing.fullname" . }
  labels:
    {- include "clearing.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "clearing.selectorLabels" . | nindent 6 }
