apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "marketmaking.fullname" . }}
  labels:
    {{- include "marketmaking.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "marketmaking.selectorLabels" . | nindent 6 }}