apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: { app: {{ .Chart.Name }} }
spec:
  type: {{ .Values.service.type }}
  ports:
    - { port: {{ .Values.service.grpcPort }}, targetPort: grpc, name: grpc }
  selector: { app: {{ .Chart.Name }} }
