apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: {{ .Chart.Name }} }
  template:
    metadata:
      labels: { app: {{ .Chart.Name }} }
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - { name: grpc, containerPort: {{ .Values.service.grpcPort }} }
          volumeMounts:
            - { name: config, mountPath: /app/configs/catalog/ }
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap: { name: {{ .Chart.Name }}-config }
