[server]
  name = "marginlending"
  port = 9099

[database]
  driver = "mysql"
  source = "root:password@tcp(127.0.0.1:3306)/financial_margin?charset=utf8mb4&parseTime=True&loc=Local"

[log]
  level = "info"
