image:
  repository: financialtrading/auth
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  grpcPort: 9095
  httpPort: 8085
config:
  server:
    grpc_port: 9095
    http_port: 8085
  database:
    driver: "mysql"
    source: "root:root@tcp(mysql:3306)/financial_trading?charset=utf8mb4&parseTime=True&loc=Local"
  log:
    level: "info"
    format: "json"
resources:
  limits: { cpu: 100m, memory: 128Mi }
  requests: { cpu: 100m, memory: 128Mi }
