apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "notification.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {} # 默认允许集群内所有 pod 访问该服务的 Ingress (可根据安全需求进一步收紧)
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0