apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quant.fullname" . }}
  labels:
    {{- include "quant.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "quant.selectorLabels" . | nindent 6 }}