apiVersion: v1
kind: Service
metadata:
  name: {{ include "market-data-service.fullname" . }}
  labels:
    {{- include "market-data-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "market-data-service.selectorLabels" . | nindent 4 }}
