apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "primebrokerage.fullname" . }}
spec:
  hosts:
    - {{ .Values.istio.gateway.host }}
  gateways:
    - {{ include "primebrokerage.fullname" . }}-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "primebrokerage.fullname" . }}
            port:
              number: {{ .Values.service.port }}
          weight: 100
      retries:
        attempts: 3
        perTryTimeout: 2s
      timeout: 10s
