apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aml.fullname" . }}-secret
  labels:
    {{- include "aml.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.config.database.password | default "" | b64enc | quote }}
  redis-password: {{ .Values.config.redis.password | default "" | b64enc | quote }}
  api-keys: {{ .Values.config.apiKeys | default "" | b64enc | quote }}
