{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aml.serviceAccountName" . }}
  labels:
    {{- include "aml.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
