[server]
name = "tradereconciliation-service"
environment = "dev"
zone = "shanghai"

[http]
addr = ":8093"
timeout = "5s"

[grpc]
addr = ":9013"
timeout = "5s"

[mysql]
dsn = "root:root@tcp(127.0.0.1:3306)/financial_reconciliation?charset=utf8mb4&parseTime=True&loc=Local"
